owner: b4sol
repo: uptime


sites:
  - name: WordPress Grillo
    url: https://www.centroigp.it/
  - name: Dolibarr Grillo
    url: https://gestionale.centroigp.it/
  - name: SuiteCRM JRS
    url: https://core.jrsconsulting.cloud/
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true
